apiVersion: v1
kind: ConfigMap
metadata:
  namespace: chunya
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      
      location / {
        return 200 "Chunya Pao";
      }
    }
